[algokit]
min_version = "v2.0.0"

[project]
type = 'contract'
name = 'FlashLoanLSig'
artifacts = 'contracts/artifacts'

[project.run]
build = { commands = [
  'npm run build',
], description = 'Compile all smart contracts in the project' }
test = { commands = [
  'npm run test',
], description = 'Run smart contract tests' }
